groups:
  - name: mlops-alerts
    rules:
      - alert: HighErrorRate
        expr: error_count{endpoint="/predict"} > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in prediction API"
          description: "Prediction API has a high error rate (> 5 errors in 5m)"

      - alert: HighLatency
        expr: prediction_latency_gauge > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High prediction latency"
          description: "Average prediction latency is above 500ms"

      - alert: DataDrift
        expr: prediction_drift_score > 0.7
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Data drift detected"
          description: "Data drift score is above 0.7, indicating significant drift"

      - alert: APIDown
        expr: up{job="mlops-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MLOps API is down"
          description: "MLOps API has been down for more than 1 minute"
